name: Har Pito
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 360
    steps:
    - name: Download Ngrok
      shell: pwsh
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive -LiteralPath ngrok.zip -DestinationPath . -Force

    # Cari ngrok.exe di mana pun berada lalu export ke env NGROK_EXE
    - name: "Detect ngrok.exe path"
      shell: pwsh
      run: |
        $ng = Get-ChildItem -Recurse -File -Filter ngrok.exe | Select-Object -First 1
        if (-not $ng) { Write-Error "ngrok.exe not found after unzip"; exit 1 }
        "NGROK_EXE=$($ng.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        Write-Host "Using NGROK_EXE at: $($ng.FullName)"

    - name: "Debug: check NGROK_AUTH_TOKEN presence"
      shell: pwsh
      run: |
        if ($Env:NGROK_AUTH_TOKEN) {
          Write-Output "::add-mask::$Env:NGROK_AUTH_TOKEN"
          Write-Host "NGROK_AUTH_TOKEN: SET (length=$($Env:NGROK_AUTH_TOKEN.Length))"
        } else { Write-Host "NGROK_AUTH_TOKEN: NOT SET"; exit 1 }
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Connect Ngrok (save authtoken)
      shell: pwsh
      run: |
        & "$Env:NGROK_EXE" authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP + create user
      shell: pwsh
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-Service -Name TermService -StartupType Automatic
        Start-Service TermService
        $pwd = $Env:RDP_PASSWORD
        if ([string]::IsNullOrWhiteSpace($pwd)) { $pwd = '@HarApito' }
        net user rdpuser $pwd /add
        net localgroup administrators rdpuser /add
        if ($Env:RDP_PASSWORD) { Write-Output "::add-mask::$pwd" }
      env:
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Start ngrok TCP 3389 in background (log to file)
      shell: pwsh
      run: |
        $p = Start-Process -FilePath "$Env:NGROK_EXE" -ArgumentList "tcp 3389 --region ap --log=stdout" -RedirectStandardOutput "ngrok.log" -RedirectStandardError "ngrok.err" -WindowStyle Hidden -PassThru
        Write-Host "Started ngrok PID=$($p.Id)"

    - name: RDP INFO LOGIN
      shell: pwsh
      run: |
        $deadline = (Get-Date).AddMinutes(2)
        $tunnel = $null
        while ((Get-Date) -lt $deadline) {
          if (Test-Path ngrok.log) {
            $m = Select-String -Path ngrok.log -Pattern 'url=tcp://([^\s]+)' | Select-Object -Last 1
            if ($m) { $tunnel = ($m.Matches[0].Groups[1].Value); break }
          }
          Start-Sleep -Seconds 2
        }
        if (-not $tunnel) {
          Write-Host "NGROK LOG (tail):"
          Get-Content ngrok.log -ErrorAction SilentlyContinue | Select-Object -Last 50
          Write-Host "NGROK ERR (tail):"
          Get-Content ngrok.err -ErrorAction SilentlyContinue | Select-Object -Last 50
          Write-Error "Gagal mendapatkan alamat ngrok TCP. Cek token/region atau terminate tunnel lama di dashboard ngrok."
          exit 1
        }
        $host,$port = ($tunnel -replace '^tcp://','').Split(':')
        $pwdShown = if ($Env:RDP_PASSWORD) { '(from secret RDP_PASSWORD)' } else { '@HarApito' }
        Write-Host "`n================= RDP INFO LOGIN ================="
        Write-Host "Host / IP  : $host"
        Write-Host "Port       : $port"
        Write-Host "Username   : rdpuser"
        Write-Host "Password   : $pwdShown"
        Write-Host "==================================================`n"

    - name: Keep alive (jangan tutup halaman Actions)
      shell: pwsh
      run: |
        while ($true) { Write-Host "RDP alive $(Get-Date -Format HH:mm:ss)"; Start-Sleep -Seconds 300 }
